# Generated by Django 4.2.14 on 2024-07-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='station',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
